server:
  port: 8080

spring:
  application:
    name: phone_shop_server

  # ===============================
  # ========== DATABASE ==========
  # ===============================
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};trustServerCertificate=true;databaseName=${DB_NAME:phone_shop_server}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}

  # ===============================
  # ========== JPA ===============
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

  # ===============================
  # ========== CACHE =============
  # ===============================
  cache:
    type: simple

    # ========== Mail    ============
    # ===============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: toandang1704@gmail.com
    password: ywmiuwykyypssucu
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false
            checkserveridentity: false
            trust: "*"

# ===============================
# ========== SWAGGER ============
# ===============================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

zalopay:
  appid: 553
  key1: 9phuAOYhan4urywHTh0ndEXiV3pKHr5Q
  key2: Iyz2habzyr7AG8SgvoBCbKwKi3UzlLi3
  url: https://sandbox.zalopay.com.vn/v001/tpe
